[project]
name = "bbw-chat-mcp"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Louis", email = "louislastella6@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=4.0.0",
    "synology-api>=0.9.2",
]

[project.scripts]
bbw-chat-mcp = "bbw_chat_mcp:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
